spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: nacos-consumer
server:
  port: 18761
management:
  endpoints:
    web:
      exposure:
        include: "*"