#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#      config:
#        server-addr: localhost:8848
#        group: DEFAULT_GROUP
#        file-extension: yaml
#  application:
#    name: nacos-consumer
#server:
#  port: 18763
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"