spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


  application:
    name: nacos-consumer-feign
server:
  port: 18763
management:
  endpoints:
    web:
      exposure:
        include: "*"
